dubbo:
  application:
    logger: slf4j
    name: fileService
    qos-enable: false
    check-serializable: false
  registry:
    address: nacos://${nacos.address:10.21.32.14}:8848?username=nacos&password=nacos
  protocol:
    port: 20885
    name: tri
  consumer:
    check: false

spring:
  main:
    web-application-type: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.address:10.21.32.17}:3306/small_potato_file?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# 日志配置
logging:
  file:
    path: ./logs
    max-history: 7
  level:
    root: info
    org.tsukilc: debug

# MyBatis-Plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



# S3配置
s3:
  endpoint: http://10.21.32.14:9030
  public-endpoint: http://10.21.32.14:9030
  region: us-east-1
  bucket: potato
  url-expiration: 3600