dubbo:
  application:
    logger: slf4j
    name: interactionService
    qos-enable: false
    check-serializable: false
  registry:
    address: nacos://${nacos.address:10.21.32.14}:8848?username=nacos&password=nacos
  protocol:
    port: 20884
    name: tri
    triple:
      rest:
        cors:
          allowed-origins: "*"
          allowed-methods: "*"
          allowed-headers: "*"
          allow-credentials: false
  consumer:
    check: false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.address:10.21.32.17}:3306/small_potato_interaction?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # Redis配置
  data:
    redis:
      host: ${redis.host:10.21.32.15}
      port: ${redis.port:6379}
      password: ${redis.password:}
      database: 0
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

# RocketMQ配置已迁移到common模块中的MQConstant常量类，使用Java SDK直接连接

# 日志配置
logging:
  file:
    path: ./logs
    max-history: 7
  level:
    root: info
    org.tsukilc: debug

# MyBatis-Plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml

server:
  port: 8083 